#AL INGRESEAR EL CUADERNO ADECUADO
# MOSTRAR EN PANTALLA EL CUADERNO ES MUY BUENO

CUADERNO=""
CUADERNO_INVALIDO=(CUADERNO!="STANFORD")
while(CUADERNO_INVALIDO):
    CUADERNO=str(input("INGRESE EL MODELO DEL CUADERNO:"))
    CUADERNO_INVALIDO=(CUADERNO!="STANFORD")
#fin_while
print("EL CUADERNO ES MUY BUENO")



