#INGRESEAR LA UBICACION
#SI SABE UBICARSE MOSTRAR EN PANTALLA TIENES BUENA ORIENTACION

UBICACION=""
UBICACION_INVALIDA=(UBICACION!="HOSPITAL BELEN")
while(UBICACION_INVALIDA):
    UBICACION=str(input("INGRESE LA UBICACION :"))
    UBICACION_INVALIDA=(UBICACION!="HOSPITAL BELEN" )
#fin_while
print("TINES MUY BUENA ORIENTACION ")

