#SOLO LAS PERSONAS CON EL PESO MAYOR A 120 KG  DEBERAN HACER DIETA
#MOSTRAR EN PANTALLA TIENES QUE HACER UNA DERIVACION GASTRICA
PESO=0.0
PESO_INVALIDO=(PESO<120)
while(PESO_INVALIDO):
    PESO=float(input("INGRESAR EL PESO DE LA PERSONA:"))
    PESO_INVALIDO=(PESO<120)
#fin_while
print("PACIENTE QUE TIENE QUE HACERSE UNA DERIVACION GASTRICA")
